std_msgs/String joint1
std_msgs/Float32 x1
std_msgs/Float32 y1
std_msgs/Float32 z1

std_msgs/String joint2
std_msgs/Float32 x2
std_msgs/Float32 y2
std_msgs/Float32 z2

std_msgs/String joint3
std_msgs/Float32 x3
std_msgs/Float32 y3
std_msgs/Float32 z3

std_msgs/String joint4
std_msgs/Float32 x4
std_msgs/Float32 y4
std_msgs/Float32 z4

std_msgs/String joint5
std_msgs/Float32 x5
std_msgs/Float32 y5
std_msgs/Float32 z5

std_msgs/String joint6
std_msgs/Float32 x6
std_msgs/Float32 y6
std_msgs/Float32 z6
